services:
  chromium:
    image: ghcr.io/averato/vending-chromium:latest
    privileged: true
    restart: unless-stopped
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/dbus:/run/dbus
      - /dev:/dev
      - /sys:/sys:ro
      - /dev/shm:/dev/shm
      - /run/udev:/run/udev:ro
    devices:
      - /dev/bus/usb
      - /dev/usb
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - APP_DEVICE_ID=${APP_DEVICE_ID}
      - XAUTHORITY=${HOME}/.Xauthority
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket # removes the wrong address warning
    entrypoint:
      - chromium
      - --incognito
      - --disable-dev-shm-usage
      - --kiosk
      - --disable-background-networking
      - --disable-plugins
      - --no-pings
      - --disable-translate
      - --disable-session-crashed-bubble
      - --noerrdialogs
      - --disable-infobars
      - --disable-fre
      - --no-default-browser-check-
      - --no-first-run
      - --disable-pinch
      - --overscroll-history-navigation=0
      - --no-context-menu
      - https://api.dev.averato.com/vending-menu/${APP_DEVICE_ID}

  app:
    image: ghcr.io/averato/vending-raspberry:latest
    privileged: true
    restart: unless-stopped
    devices:
      - /dev/gpiochip0
    volumes:
      - /dev:/dev
      - /sys:/sys
    ports:
      - 8888:8888
    environment:
      - APP_MQTT_DOMAIN=${APP_MQTT_DOMAIN}
      - APP_MQTT_USER=${APP_MQTT_USER}
      - APP_MQTT_PASSWORD=${APP_MQTT_PASSWORD}
      - APP_MQTT_PORT=${APP_MQTT_PORT}
      - APP_DEVICE_ID=${APP_DEVICE_ID}
